
CREATE DATABASE cinemax;

CREATE TABLE IF NOT EXISTS cinemax.user (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	email VARCHAR(128) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	birth_date TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS cinemax.room (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	capacity INT(10) DEFAULT 100
);

CREATE TABLE IF NOT EXISTS cinemax.movie (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL,
	`version` VARCHAR(64) NOT NULL,
	vision VARCHAR(128) NOT NULL,
	duration FLOAT(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS cinemax.ticket (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	movie_id INT(10) NOT NULL,
	user_id INT(10) NOT NULL,
	price FLOAT(10) NOT NULL,
	created_date TIME NOT NULL,
	FOREIGN KEY FK_TicketMovie(movie_id)
	REFERENCES movie(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY FK_TicketUser(user_id)
	REFERENCES user(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS cinemax.session (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	start_date TIME NOT NULL,
	movie_id INT(10) NOT NULL,
	room_id INT(10) NOT NULL,
	ticket_count INT(10) NOT NULL DEFAULT 0,
	FOREIGN KEY FK_SessionMovie(movie_id)
	REFERENCES movie(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY FK_SessionRoom(room_id)
	REFERENCES room(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);